#!/bin/sh

set -x

GIT_VER=$(gitver)

cd ..

tar czvf /tmp/portgen_java-${GIT_VER}.tgz portgen_java/{LICENSE,README.adoc,mkdist,portgen_java,portgen_java.1,settings-global.xml,settings.template,specification.adoc}
