#!/bin/sh

set -x

GIT_VER=1.1.0
TAR=/tmp/portgen_java-${GIT_VER}.tgz 
cd ..

tar czvf ${TAR} portgen_java/{LICENSE,README.adoc,mkdist,portgen_java,portgen_java.1,settings-global.xml,settings.template,specification.adoc}

scp $TAR dos:/var/www/htdocs/darwinsys.com/portgen_java
