= portgen_java

A simple Java program to generate an OpenBSD port to build a package from a Java
program that has a pom file but doesn't offer precompiled packages or for which
those are not trusted by the porter.

This cannot go into base because it depends on a Java port (e.g., jdk-25) being installed.

== Usage

	portgen_java [-u][-d][-v][-k] target-pom

The given target-pom file should build the app as a single artifact, normally via an
`assembly:single` task to build a finished jar.

Options:

* -d - debugging output
* -u - update the generated port directory
* -k - keep the temporary local repostiroy (it is by default deleted at the end)
* -u - verbose - information less detailed than the debugging output.

== What it does

Checks for, and reads, the pom file in the target directory. Extracts the name and version.

Runs maven with some options to get the list of dependencies.

Plugs the name and version into a minimal `Makefile`, along with the list of deps,
and saves the Makefile under `/usr/ports/mystuff/java/NAME/Makefile`, where `NAME` is
the name element at the top of the `pom` file.

== What it does not do

Due to the huge variability of Java programs,
the generated `Makefile` will need considerable editing.

This program doesn't yet generate (but these are trivial):

* for programs, a run script in /usr/local/bin and a desktop file for GUI start;
* for services, an `/etc/rc.d` file.

== Future Work

=== Base Portgen is written in Perl

Perl can call Java, using `Inline::Java` - if we had that in base, this could be
called directly from the existing portgen.

Alternately, if somebody wants to manually (not using AI) translate this into Perl,
it could be added as a module into the standard perl-based `portgen` in base.
But then you get to take over as maintainer!
